name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.sb99CLRcpulkZL51FeA6OhJp }}
      VERCEL_PROJECT_ID: ${{ secrets.prj_JE7PyoU3iEaCqbrp5NoHVUAz0bbr }}
      VERCEL_TOKEN: ${{ secrets.bNGKIQGtdnl8eKL7XmxLcgmV }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build Project Artifacts
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN